### ISSUE TITLE
[BUG] Discord bot /inv not working

### ISSUE THREAD

**Issue by TrollCLGT** [hrfee/jfa-go#378]
Jellyfin 10.10.3 running as a LXC container in Proxmox, installed via [this script](https://tteck.github.io/Proxmox/)
jfa-go 0.5.1 stable installed on the same LXC
Discord stable 348981 (ff756ae)

Problem: /inv command not working in Discord
![jfa-go-1](https://github.com/user-attachments/assets/44e8caab-5b4d-45ab-a8b7-c0453a129c3c)

How to reproduce the issue:
Follow [these steps](https://wiki.jfa-go.com/docs/bots/discord/#1-create-an-application)
No "Authorization Method" and no "Read Message/View Channels" options
![jfa-go-2](https://github.com/user-attachments/assets/4ba5565f-635f-47ae-a7fa-4f6007e773cd)
![jfa-go-3](https://github.com/user-attachments/assets/7f4dc6e9-d69b-4979-a864-1995f96fd565)

Jfa-go settings for Discord:
![jfa-go-4](https://github.com/user-attachments/assets/2913dd7e-000a-44d5-a7cc-96b3aa15c983)

**Comment by 0belous** [comment]
Did you find a solution?

**Comment by TrollCLGT** [comment]
Installing the unstable branch works for me.

**Comment by raku-cat** [comment]
Not working here either, setup as below:

![Image](https://github.com/user-attachments/assets/c68d1e71-77c3-4663-a304-a6ad13453a89)
Added to server with https://discord.com/oauth2/authorize?client_id=[REDACTED]&integration_type=0&scope=bot&permissions=1127824320752641

![Image](https://github.com/user-attachments/assets/ad237013-9278-4f5a-8651-d3a0674ba866)

(went a little overkill as part of debugging, though i started with the wiki listed perms.

Other commands run fine, but when I try inv on a user that has access to the channel the bot is in:

![Image](https://github.com/user-attachments/assets/2bfe9f09-d488-4b6e-9b61-1faafa55eab0)

Invite gets created in jfa-go admin dash, I can see one as "DIscord: @[username i picked]", that's about it though, even with debug logging on there's nothing logged when the commands is ran.
Tried compiling latest git main as suggested above:

![Image](https://github.com/user-attachments/assets/ce34cc66-4082-4d39-a207-ce2f00b429f3)

It behaves the same.

**Comment by TrollCLGT** [comment]
It's been a long time since I first set this up so there has been updates to the unstable branch. Here's is a screenshot of my jfa-go version:

![Image](https://github.com/user-attachments/assets/c685f716-2d89-426f-9559-7f8ae21d77d7)

If you really want to test out with my outdated image, feel free to download it here:

[https://drive.google.com/file/d/1Nbxl-w62Zapq3TIqu62-5K0xc5kN0pXw/view?usp=drive_link](url)

I can confirm that the /inv is still working for me on this image. If it still doesn't work then it might be some configuration issues on your end.

**Comment by raku-cat** [comment]
> It's been a long time since I first set this up so there has been updates to the unstable branch. Here's is a screenshot of my jfa-go version:
> 
> ![Image](https://github.com/user-attachments/assets/c685f716-2d89-426f-9559-7f8ae21d77d7)
> 
> If you really want to test out with my outdated image, feel free to download it here:
> 
> [https://drive.google.com/file/d/1Nbxl-w62Zapq3TIqu62-5K0xc5kN0pXw/view?usp=drive_link](url)
> 
> I can confirm that the /inv is still working for me on this image. If it still doesn't work then it might be some configuration issues on your end.

I'll give it a shot I suppose but ya I agree, I assume it's a configuration nuance, perhaps a change in discord API that needs a specific config that just needs to be documented.

**Comment by hrfee** [comment]
Sorry, I guess I didn't review this well enough when it was PRed and I missed that it checked locally whether the user was a jfa-go admin, (i.e. not a Jellyfin admin, but had had "access jfa-go" checked by their name in Accounts), rather than in all relevant locations (i.e. the same way it's done when you try to log into the admin page). That commit should fix it, could you all try? Thanks.

**Comment by raku-cat** [comment]
> Sorry, I guess I didn't review this well enough when it was PRed and I missed that it checked locally whether the user was a jfa-go admin, (i.e. not a Jellyfin admin, but had had "access jfa-go" checked by their name in Accounts), rather than in all relevant locations (i.e. the same way it's done when you try to log into the admin page). That commit should fix it, could you all try? Thanks.

Built latest master, the webui fails to load (white screen) and the command gives the same error, though I'm assuming for different reasons now, and gives no errors for either issue in the logs.

**Comment by raku-cat** [comment]
Not sure if it was because of 07d02f8 but I just rebuilt after making some adjustments to my compilation process and the webui loads now, but still not having inv command give "application did not respond", I will note though that now the invites aren't even being silently created in the webui like before.
Just to clarify how I'm setup, I login with my jellyfin login, which is a jellyfin admin account, and that account is the one marked "access jfa-go" in the ui, and also is the one linked to my discord that I'm trying the command from.

In verifying all of the above, I found that when I manually unliked my discord from admin account and then tried to add it back, when i typed my username and then clicked add, I get a red error in the bottom right corner with the following in logs:
```
May 15 14:15:58 partyvan jfa-go[578046]: [GIN] DELETE(/users/discord) => 500 <--- unlinking discord
May 15 14:15:58 partyvan jfa-go[578046]: [GIN] GET(/users/announce) => 200
May 15 14:15:58 partyvan jfa-go[578046]: [GIN] GET(/users/announce) => 200
May 15 14:15:58 partyvan jfa-go[578046]: [GIN] GET(/users) => 200
May 15 14:15:58 partyvan jfa-go[578046]: [GIN] GET(/users) => 200
May 15 14:16:01 partyvan jfa-go[578046]: [GIN] GET(/accounts) => 200
May 15 14:16:01 partyvan jfa-go[578046]: [GIN] GET(/lang/admin) => 200
May 15 14:16:01 partyvan jfa-go[578046]: [INFO] 14:16:01  Token requested (refresh token)
May 15 14:16:01 partyvan jfa-go[578046]: [GIN] GET(/token/refresh) => 200
May 15 14:16:01 partyvan jfa-go[578046]: [GIN] GET(/config/update) => 200
May 15 14:16:01 partyvan jfa-go[578046]: [GIN] GET(/users/announce) => 200
May 15 14:16:01 partyvan jfa-go[578046]: [GIN] GET(/profiles/names) => 200
May 15 14:16:01 partyvan jfa-go[578046]: [GIN] GET(/users) => 200 <--- refreshing the page
May 15 14:16:08 partyvan jfa-go[578046]: [GIN] GET(/users/discord/raku) => 200
May 15 14:16:10 partyvan jfa-go[578046]: 2025/05/15 14:16:10 [Recovery] 2025/05/15 - 14:16:10 panic recovered: <-- error after clicking add
May 15 14:16:10 partyvan jfa-go[578046]: runtime error: invalid memory address or nil pointer dereference
May 15 14:16:10 partyvan jfa-go[578046]: /usr/lib/go/src/runtime/panic.go:262 (0x4808d8)
May 15 14:16:10 partyvan jfa-go[578046]:         panicmem: panic(memoryError)
May 15 14:16:10 partyvan jfa-go[578046]: /usr/lib/go/src/runtime/signal_unix.go:925 (0x4808a8)
May 15 14:16:10 partyvan jfa-go[578046]:         sigpanic: panicmem()
May 15 14:16:10 partyvan jfa-go[578046]: /home/glizzy/aur/jfa-go-git/src/jfa-go-git/api-messages.go:683 (0xf48ca2)
May 15 14:16:10 partyvan jfa-go[578046]: /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0xf66ec5)
May 15 14:16:10 partyvan jfa-go[578046]:         (*Context).Next: c.handlers[c.index](c)
May 15 14:16:10 partyvan jfa-go[578046]: /home/glizzy/aur/jfa-go-git/src/jfa-go-git/auth.go:138 (0xf66de6)
May 15 14:16:10 partyvan jfa-go[578046]: /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x98b7ae)
May 15 14:16:10 partyvan jfa-go[578046]:         (*Context).Next: c.handlers[c.index](c)
May 15 14:16:10 partyvan jfa-go[578046]: /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102 (0x98b79b)
May 15 14:16:10 partyvan jfa-go[578046]:         CustomRecoveryWithWriter.func1: c.Next()
May 15 14:16:10 partyvan jfa-go[578046]: /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x98a8e4)
May 15 14:16:10 partyvan jfa-go[578046]:         (*Context).Next: c.handlers[c.index](c)
May 15 14:16:10 partyvan jfa-go[578046]: /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249 (0x98a8cb)
May 15 14:16:10 partyvan jfa-go[578046]:         LoggerWithConfig.func1: c.Next()
May 15 14:16:10 partyvan jfa-go[578046]: /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x989cf1)
May 15 14:16:10 partyvan jfa-go[578046]:         (*Context).Next: c.handlers[c.index](c)
May 15 14:16:10 partyvan jfa-go[578046]: /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633 (0x989780)
May 15 14:16:10 partyvan jfa-go[578046]:         (*Engine).handleHTTPRequest: c.Next()
May 15 14:16:10 partyvan jfa-go[578046]: /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589 (0x9892a9)
May 15 14:16:10 partyvan jfa-go[578046]:         (*Engine).ServeHTTP: engine.handleHTTPRequest(c)
May 15 14:16:10 partyvan jfa-go[578046]: /usr/lib/go/src/net/http/server.go:3301 (0x72ac2d)
May 15 14:16:10 partyvan jfa-go[578046]:         serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
May 15 14:16:10 partyvan jfa-go[578046]: /usr/lib/go/src/net/http/server.go:2102 (0x7096e4)
May 15 14:16:10 partyvan jfa-go[578046]:         (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
May 15 14:16:10 partyvan jfa-go[578046]: /usr/lib/go/src/runtime/asm_amd64.s:1700 (0x486ae0)
May 15 14:16:10 partyvan jfa-go[578046]:         goexit: BYTE        $0x90        // NOP
May 15 14:16:10 partyvan jfa-go[578046]: 
May 15 14:16:10 partyvan jfa-go[578046]: [GIN] POST(/users/discord) => 500
May 15 14:16:10 partyvan jfa-go[578046]: [GIN] GET(/users/announce) => 200
May 15 14:16:10 partyvan jfa-go[578046]: [GIN] GET(/users) => 200 <-- refresh
```
After refreshing the page or closing the dialog though, the discord account is still shown on my account as though I'd linked it.
Similar effect happens from trying to link in the My Account area, though this time it offers a code, when I go through the linking process with the bot it gives an error in the logs, and then shows no indication on the webui that its worked, but after refreshing it shows my account as linked.

**Comment by raku-cat** [comment]
Apologies for comment spam, I've gone through and re-added my bot with the following settings per the wiki [here](https://wiki.jfa-go.com/docs/external-services/bots/discord/) as shown:
<details>
<summary>Privileged permissions (tried to adapt the instructions, assuming it needs message content intent)</summary>

![Image](https://github.com/user-attachments/assets/544e7e21-50ff-4199-91a2-4ac74b0456fd)

</details>
<details>
<summary>Bot/oauth perms</summary>

![Image](https://github.com/user-attachments/assets/da535207-7c00-4041-9bd4-183cbec84eb8)

</details>
And after that, I

**Comment by raku-cat** [comment]
> It's been a long time since I first set this up so there has been updates to the unstable branch. Here's is a screenshot of my jfa-go version:
> 
> <image>
> 
> If you really want to test out with my outdated image, feel free to download it here:
> 
> [https://drive.google.com/file/d/1Nbxl-w62Zapq3TIqu62-5K0xc5kN0pXw/view?usp=drive_link](url)
> 
> I can confirm that the /inv is still working for me on this image. If it still doesn't work then it might be some configuration issues on your end.

Forgot to test this, got docker set up and gave this image a shot, to my surprise invites work!

![Image](https://github.com/user-attachments/assets/98ecadc2-e01b-41de-844f-937f2ae4ade6)

So I'm very confused, I did have to kick and re-add my bot, but I used identical bot permissions as I've shown above, so the only change was the jfa-go version. 
Just a glance over the diff of the two ([here](https://github.com/hrfee/jfa-go/compare/0ccc314...07d02f8#files_bucket)) doesn't show anything obvious, but I've spent a bit of time fiddling around.
On a hunch, I moved my jfa config from my currently running verison to re-trigger the onboarding and to my surprise, the invites also worked!
I then narrowed this down to a quirk in the config.ini, and diffed the new config.ini and my old existing one, and based on that, went and enabled `Invite emails`:

![Image](https://github.com/user-attachments/assets/863c12e0-aac2-4278-81e2-8832a2088a9c)

And it works now!
So this seems to be the issue, maybe an older version of jfa during the onboarding wouldn't enable this or maybe I turned it off manually, but it is a little confusing regardless that global invite enabled/disabled is controlled by a setting area named "Invite emails" so it probably just needs a wording change or perhaps make it so this global "invite enabled" state is controlled by if any of the invite methods are enabled.

**Comment by hrfee** [comment]
No problem. I've updated the Wiki where necessary, I hate how often Discord changes their API & developer portal. You can disable that privileged "Read Messages" server gateway intent though,  Slash commands don't count as messages so no such permission is needed.

**Comment by raku-cat** [comment]
> > Ya the two times I've tried to make alts using some of my other emails have resulted in instabans... Fun times. For the second one, they aren't supposed to DM but that user wasn't getting ANY dm so I had them dm to double check if it was needed, I think that one was some weird setting they had on their account, I haven't had it happen with anyone else.a
> 
> Ah okay fair enough. Thats the sorta thing where i'd need logs from the time it happened, any issues with sending messages should get logged. If it happens again, which hopefully it doesn't, it'd be appreciated if you could trawl through your logs. Thank you again by the way.
 
Will do! Probably will open new bug report for that, this one's probably a little past its prime lol
